xychart-beta
    title "Burn up chart"
    x-axis "Sessions" [0, 1, 2, 3, 4, 5, 6, 7, 8]
    y-axis "Points" 0 --> 176
    line "Goal" [0, 36, 69]
    line "Real" [0]
    line "Theory" [0, 22, 44, 66, 88, 110, 132, 154, 177]
